sudo: require
services:
- docker
before_install:
- docker pull node:8-onbuild
install:
- docker build -t probot-hello .
script:
- docker run --rm probot-hello npm run test
- docker run --rm probot-hello npm run lint
deploy:
  provider: heroku
  api_key:
    secure: tyGLc5YYO7Zwkd3ALpUO0+tVYW+it6geoHuAtkMpv91Q7HuAdYJ6lnBxMPjjAcXaVzdOe64cGJ4NRtXUOKSu9j/e11vVM+K0rA1ChNQAtZQiBHARgyBPOQJvMML5SqYGP0M2qsf1GENejkb+H6A9AUhc4QgXKGjrjwslOYhC0PxQnVSDXtMMh2eWgUDPVFI8H6qskPKwZIux3Nx81fKLxFW2J5S3Fe2f0jVscZFdkwo/3YZiFZKIEL3ePMPjZshi00N6Jh+S2SBryA8WsukacRNDoOVSZtTUTyfHXFH/HIl7EqtE0FRAyz0w4/kgiCoRA1o4nFagLeTTg1nyyWWD7AuH/zf0tmXCLXs7HOE3D9EcfTVoImIFK1ZVcXHSN8FFssYRouz43At/M9CKrIXw9dEIuI7VgYZzyTEbSroRIGSTMIcHycxFxdY9JaBCvn6enkdaOucGE6GNsUj7AvISnRRhHCVUTXlev/pWFDXqbyFINhK8N2WqxSPdEEaaRCXcob43Vqh7N7ntShHfePSAQLd8QfgYr6eExumCGjRf8raMhvKArr5u23+A6+q0KO9e8FiKnR4ItvU3YQgNtqMM9a0fJaDDW8njUC44+GGvaM0tk3hRWHejXp5APy/C61aOwsHyXcvskvkpsB0/+x8afPnaXn0XExEkGUunfmKA0aw=
  on: heroku_production
  app: probot-skyedat
  
